### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by xiaolongn100** [DianaNites/cargo-sysroot#2]
error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:884:13
    |
884 |             Literal::Fallback(lit) => Span::Fallback(lit.span()),
    |             ^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Fallback(lit)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0599]: no method named `span` found for type `&proc_macro::Literal` in the current scope
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:883:58
    |
883 |             Literal::Compiler(lit) => Span::Compiler(lit.span()),
    |                                                          ^^^^

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:890:14
    |
890 |             (Literal::Compiler(lit), Span::Compiler(s)) => lit.set_span(s),
    |              ^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Compiler(lit)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:891:14
    |
891 |             (Literal::Fallback(lit), Span::Fallback(s)) => lit.set_span(s),
    |              ^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Fallback(lit)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0599]: no method named `set_span` found for type `&mut proc_macro::Literal` in the current scope
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:890:64
    |
890 |             (Literal::Compiler(lit), Span::Compiler(s)) => lit.set_span(s),
    |                                                                ^^^^^^^^

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:913:13
    |
913 |             Literal::Compiler(t) => t.fmt(f),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Compiler(t)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:914:13
    |
914 |             Literal::Fallback(t) => t.fmt(f),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Fallback(t)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:922:13
    |
922 |             Literal::Compiler(t) => t.fmt(f),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Compiler(t)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/xiaolong/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proc-macro2-0.4.27/src/wrapper.rs:923:13
    |
923 |             Literal::Fallback(t) => t.fmt(f),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&Literal::Fallback(t)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error: aborting due to 41 previous errors

You've got a few errors: E0207, E0432, E0658
If you want more information on an error, try using "rustc --explain E0207"
error: aborting due to 144 previous errors

You've got a few errors: E0412, E0433, E0599, E0658
If you want more information on an error, try using "rustc --explain E0412"
error: Could not compile `serde`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-sysroot v0.5.3`, intermediate artifacts can be found at `/tmp/cargo-install.HQRiC4aCcYYK`

Caused by:
  build failed

**Comment by DianaNites** [comment]
Sorry, I completely missed this issue.

This doesn't look like a problem with cargo-sysroot at all, though. You can't compile serde either. You're rust version is probably too old, this crate only supports the latest nightly compiler.
