### ISSUE TITLE
Support running outside the context of a cargo crate

### ISSUE THREAD

**Issue by chbaker0** [DianaNites/cargo-sysroot#22]
Depending on a custom sysroot is useful even for projects that aren't built with cargo. The ability to pass all required information by flags and not need Cargo.toml would be nice.

Is this a contribution you'd accept?

**Comment by DianaNites** [comment]
Apologies, I would not accept such a contribution. This is intended solely to support Cargo, and has largely been superseded by the [native `build-std` feature](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std)

**Comment by DianaNites** [comment]
Apologies, I would not accept such a contribution. This is intended solely to support Cargo, and has largely been superseded by the [native `build-std` feature](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) anyway.
